# Generated by Django 4.1.13 on 2024-06-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_longitude', models.FloatField()),
                ('start_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='orders.order')),
            ],
        ),
    ]
