# Generated by Django 4.1.13 on 2024-06-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='map',
            table='Map',
        ),
    ]
