# Generated by Django 4.1.13 on 2024-06-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_shop_catego_name_289c7e_idx_category_name_476266_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='category_name_d601b7_idx',
            old_name='Category_name_476266_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_id_1d04b7_idx',
            old_name='Product_id_add86e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_name_c4c985_idx',
            old_name='Product_name_5f5d5c_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_created_01e61b_idx',
            old_name='Product_created_e1c2c8_idx',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
