# Generated by Django 4.1.13 on 2024-06-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_remove_courier_birth_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courier',
            table='Couriers',
        ),
    ]
