# Generated by Django 4.1.13 on 2024-06-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0004_alter_courier_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courier',
            table='couriers',
        ),
    ]
