# Generated by Django 4.1.13 on 2024-06-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='Order_created_bf319d_idx',
            old_name='orders_orde_created_743fca_idx',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItem',
        ),
    ]
