# Generated by Django 4.1.13 on 2024-06-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_orders_orde_created_743fca_idx_order_created_bf319d_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='order_created_047412_idx',
            old_name='Order_created_bf319d_idx',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='orderItem',
        ),
    ]
